defmodule WunderMatch.Matching.Location do
  @moduledoc """
  This  module holds the base Structure for all location points
  in the application it.
  It contains a coordinate which is a Geo.Point
  https://hexdocs.pm/geo/Geo.Point.html
  And and autogenerated uuid
  """

  @type t :: %__MODULE__{}

  defstruct coordinate: nil, id: UUID.uuid1()
end
